export const copy = {
  en: {
    nav: ['How it works', 'For our people', 'Questions'], join: 'Join the waitlist', coming: 'KANO & KATSINA, WE’RE COMING.',
    title: ['Good food.', 'Closer to you.'], intro: 'From the kitchens you love to wherever you are. Your next good meal is a little closer.',
    heroNote: 'First to know. First to order.', cities: 'Starting in Kano & Katsina', dish: ['Jollof & chicken', 'Golden masa'],
    dishNote: ['A little smoky. A lot of comfort.', 'For the love of a local favourite.'], taste: 'A TASTE OF WHAT’S COMING',
    pause: 'Pause motion', play: 'Resume motion', scroll: 'GOOD FOOD IS JUST THE START',
    howLabel: 'LESS RUNNING AROUND. MORE SITTING DOWN.', howTitle: 'Craving. Tap. Enjoy.',
    steps: [ ['Find your favourite.', 'Discover nearby kitchens and choose what you’re in the mood for.'], ['We’ll take it from here.', 'Your vendor prepares your food. A nearby rider picks it up.'], ['Make room at the table.', 'Follow your order all the way to your door. Then tuck in.'] ],
    channelLabel: 'YOUR PHONE. YOUR CHOICE.', channelTitle: 'Order your way.', channelBody: 'An app person? A WhatsApp person? We’re making room for both. Pick the way that feels easiest.', soon: 'Coming soon',
    communityLabel: 'THERE’S A PLACE FOR YOU HERE.', communityTitle: 'Good things happen together.', communityBody: 'The kitchen. The ride. The person who brings us together. Help us get Koola moving.',
    roles: [ ['vendor','Feed your neighbourhood.','Put your kitchen on Koola and reach more hungry people.','Become a vendor'], ['rider','Make your next move count.','Deliver around your city and keep your delivery earnings.','Ride with Koola'], ['affiliate','Bring good people together.','Introduce vendors to Koola and earn on their successful orders.','Become an affiliate'] ],
    faqTitle: 'A few things to know.', faqs: [ ['Where is Koola launching?','We’re preparing to launch in Kano and Katsina. Join the waitlist and choose your city so we can let you know when ordering opens.'], ['Can I order food yet?','Not yet. We’re bringing vendors and riders on board. Join the waitlist for launch updates.'], ['Will I need to download an app?','We’re planning web ordering, mobile apps, WhatsApp and a Telegram mini app. All are coming soon.'], ['How will delivery fees work?','You’ll see the fee before you pay. Pricing will account for distance and vehicle type. We’re testing local rates before launch.'], ['How do I become a vendor?','Choose “Vendor” in the form below. We’ll contact you about verification, your menu and getting started.'] ],
    formLabel: 'GET A SEAT AT THE TABLE.', formTitle: 'Be there for the first bite.', formBody: 'Leave your details. We’ll tell you when Koola is ready in your city.',
    name: 'Your name', email: 'Email address', phone: 'Phone number', city: 'Your city', role: 'I’m joining as a', roleNames: ['Customer','Vendor','Rider','Affiliate'], consent: 'You can contact me about Koola’s launch and my signup.', data: 'We use these details to manage your signup and contact you about launch. We do not take payment here.', submit: 'Count me in', pending: 'Saving your spot…', success: 'You’re on the list.', successBody: 'We’ve saved your signup. We’ll be in touch about Koola in your city.', another: 'Add another signup', error: 'We couldn’t save your signup. Please try again.', footer: 'Good food. Good company.', rights: 'Koola · Kano & Katsina', menu: 'Open menu', close: 'Close menu',
  },
  ha: {
    nav: ['Yadda yake aiki', 'Abokan hulɗa', 'Tambayoyi'], join: 'Shiga jerin jira', coming: 'KANO DA KATSINA, MUNA TAFE.',
    title: ['Abinci mai daɗi.', 'Kusa da kai.'], intro: 'Daga wuraren abincin da kake so zuwa inda kake. Abincinka ya ƙara zuwa kusa.',
    heroNote: 'Ka fara samun labari.', cities: 'Za mu fara a Kano da Katsina', dish: ['Jollof da kaza', 'Masa'], dishNote: ['Abinci mai daɗi da ƙamshi.', 'Abincin da muka sani kuma muke so.'], taste: 'DAGA CIKIN ABUBUWAN DA MUKA SHIRYA',
    pause: 'Dakatar da motsi', play: 'Ci gaba da motsi', scroll: 'ABINCI MAI DAƊI SHI NE FARKO',
    howLabel: 'KA HUTA, MU KAWO MAKA.', howTitle: 'Zaɓa. Yi oda. Ji daɗi.',
    steps: [ ['Zaɓi abin da kake so.', 'Duba wuraren abinci na kusa ka zaɓi abincinka.'], ['Mu za mu kula.', 'Mai sayarwa zai shirya abincinka. Mai kai kaya zai ɗauka.'], ['Shirya wurin cin abinci.', 'Bi diddigin odarka har ta iso ƙofarka.'] ],
    channelLabel: 'WAYARKA. ZAƁINKA.', channelTitle: 'Yi oda yadda kake so.', channelBody: 'Ta manhaja ko WhatsApp, muna shirya hanyoyi daban-daban domin ka zaɓi mai sauƙi a gare ka.', soon: 'Nan ba da jimawa ba',
    communityLabel: 'AKWAI WURI A GARE KA.', communityTitle: 'Mu yi aiki tare.', communityBody: 'Masu abinci, masu kai kaya da masu kawo abokan hulɗa. Ka shiga gina Koola tare da mu.',
    roles: [ ['vendor','Ka sayar wa mutanen kusa.','Saka wurin abincinka a Koola ka samu ƙarin kwastomomi.','Zama mai sayarwa'], ['rider','Yi aiki a garinka.','Kai abinci kuma ka riƙe kuɗin kai kayan da ka samu.','Zama mai kai kaya'], ['affiliate','Haɗa mu da masu abinci.','Kawo masu sayarwa Koola ka samu lada daga odarsu.','Zama abokin hulɗa'] ],
    faqTitle: 'Abubuwan da ya kamata ka sani.', faqs: [ ['A ina Koola za ta fara?','Muna shirin fara aiki a Kano da Katsina. Shiga jerin jira ka zaɓi garinka domin mu sanar da kai idan an fara.'], ['Zan iya yin oda yanzu?','Ba tukuna ba. Muna shigar da masu sayarwa da masu kai kaya. Shiga jerin jira domin samun labari.'], ['Sai na sauke manhaja?','Muna shirin ba da damar oda ta yanar gizo, manhaja, WhatsApp da Telegram. Dukkansu suna zuwa.'], ['Yaya kuɗin kai abinci zai kasance?','Za ka ga kuɗin kafin ka biya. Za a yi la’akari da nisa da irin abin hawa. Muna gwajin farashin kafin fara aiki.'], ['Ta yaya zan zama mai sayarwa?','Zaɓi “Mai sayarwa” a fom ɗin. Za mu tuntuɓe ka game da tantancewa, jerin abinci da fara aiki.'] ],
    formLabel: 'KA SHIRYA DON FARAWA.', formTitle: 'Ka fara samun labari.', formBody: 'Ka bar bayananka. Za mu sanar da kai idan Koola ta shirya a garinka.',
    name: 'Sunanka', email: 'Adireshin imel', phone: 'Lambar waya', city: 'Garinka', role: 'Ina shiga a matsayin', roleNames: ['Kwastoma','Mai sayarwa','Mai kai kaya','Abokin hulɗa'], consent: 'Na yarda a tuntuɓe ni game da fara Koola da rajistata.', data: 'Za mu yi amfani da bayananka wajen rajista da sanar da kai game da farawa. Ba ma karɓar kuɗi a nan.', submit: 'Saka ni a ciki', pending: 'Ana ajiye bayananka…', success: 'Ka shiga jerin.', successBody: 'Mun ajiye rajistarka. Za mu tuntuɓe ka game da Koola a garinka.', another: 'Ƙara wata rajista', error: 'Ba mu samu ajiye rajistarka ba. Ka sake gwadawa.', footer: 'Abinci mai daɗi. Tare da juna.', rights: 'Koola · Kano da Katsina', menu: 'Buɗe menu', close: 'Rufe menu',
  }
} as const;
export type Lang = keyof typeof copy;
export type Role = 'customer' | 'vendor' | 'rider' | 'affiliate';
