const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const previewUrl = process.env.LANDING_PREVIEW_URL || 'http://localhost:8787/';
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror', e=>errors.push(e.message));
 await page.goto(previewUrl,{waitUntil:'networkidle'});
 await page.getByRole('heading',{name:'Good food. Closer to you.',exact:true}).waitFor();
 await page.getByRole('button',{name:'Pause motion'}).click();
 await page.screenshot({path:'artifacts/landing-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Golden masa',exact:true}).click();
 assert(await page.getByRole('img',{name:'Golden masa with pepper dipping sauce on a cream plate'}).isVisible());
 await page.getByRole('button',{name:'Switch to Hausa'}).click();
 assert.equal(await page.locator('html').getAttribute('lang'),'ha');
 assert(await page.getByRole('heading',{name:'Abinci mai daɗi. Kusa da kai.'}).isVisible());
 await page.getByRole('button',{name:'Switch to English'}).click();
 await page.getByRole('button',{name:'Become a vendor',exact:true}).click();
 assert(await page.getByRole('radio',{name:'Vendor',exact:true}).isChecked());
 await page.getByLabel('Your name',{exact:true}).fill('Koola UI Test');
 await page.getByLabel('Email address',{exact:true}).fill(`koola-ui-${Date.now()}@example.invalid`);
 await page.getByLabel('Phone number',{exact:true}).fill('08031234567');
 await page.getByRole('combobox',{name:'Your city'}).click();
 await page.getByRole('option',{name:'Kano'}).click();
 await page.getByRole('checkbox').check();
 await page.route('**/api/leads',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})}));
 const response=page.waitForResponse(r=>r.url().endsWith('/api/leads')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Count me in'}).click();
 assert.equal((await response).status(),200);
 await page.getByRole('heading',{name:'You’re on the list.'}).waitFor();
 await page.unroute('**/api/leads');
 await page.getByRole('button',{name:'Add another signup'}).click();
 await page.getByLabel('Your name',{exact:true}).fill('Koola UI Test');
 await page.getByLabel('Email address',{exact:true}).fill('koola-failure@example.invalid');
 await page.getByLabel('Phone number',{exact:true}).fill('08031234567');
 await page.getByRole('combobox',{name:'Your city'}).click();
 await page.getByRole('option',{name:'Katsina'}).click();
 await page.getByRole('checkbox').check();
 await page.route('**/api/leads',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'service_unavailable'})}));
 await page.getByRole('button',{name:'Count me in'}).click();
 await page.locator('.form-error[role=alert]').waitFor();
 await expect(page.locator('.form-error[role=alert]')).toHaveText('Signups are temporarily unavailable. Please try again shortly.');
 assert(!(await page.getByRole('heading',{name:'You’re on the list.'}).count()));
 await page.unroute('**/api/leads');
 for(const width of [320,390,768,1024,1440]) {
  await page.setViewportSize({width,height:900});
  await page.evaluate(()=>scrollTo(0,0));
  const measure=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
  assert(measure.scroll<=measure.width,JSON.stringify(measure));
 }
 await page.setViewportSize({width:390,height:844});
 await page.goto(previewUrl,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Pause motion'}).click();
 await page.getByRole('button',{name:'Open menu'}).click();
 await page.getByRole('navigation').getByRole('link',{name:'How it works'}).click();
 assert.equal(await page.getByRole('button',{name:'Open menu'}).getAttribute('aria-expanded'),'false');
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:'artifacts/landing-mobile.png',fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.reload({waitUntil:'networkidle'});
 const a=await page.locator('.plate-float').evaluate(el=>getComputedStyle(el).transform);
 await page.waitForTimeout(150);
 const b=await page.locator('.plate-float').evaluate(el=>getComputedStyle(el).transform);
 assert.equal(a,b);
 assert.deepEqual(errors,[]);
 console.log('PASS: local preview, dish switch, EN/HA, role preselection, mocked signup success/error states, mobile menu, 320/390/768/1024/1440 overflow checks, reduced motion, no page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
